apiVersion: v1
kind: Namespace
metadata:
  name: anythingllm
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anythingllm-storage
  namespace: anythingllm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: anythingllm
  namespace: anythingllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anythingllm
  template:
    metadata:
      labels:
        app: anythingllm
    spec:
      containers:
      - name: anythingllm
        image: mintplexlabs/anythingllm
        ports:
        - containerPort: 3001
        volumeMounts:
        - name: storage
          mountPath: /app/server/storage
        env:
        - name: STORAGE_DIR
          value: /app/server/storage
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: anythingllm-storage
---
apiVersion: v1
kind: Service
metadata:
  name: anythingllm-service
  namespace: anythingllm
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001
  selector:
    app: anythingllm